### ISSUE TITLE
ValueError: CSRF token not found

### ISSUE THREAD

**Issue by CSCyril** [borys25ol/amazon-location-cookies-service#4]
Hello,
First off all, thank you for your work.
I'm trying to make it work with amazon.de, but at every try I get an error on the script :

```
ERROR: Spider error processing <GET https://www.amazon.de/portal-migration/hz/glow/get-rendered-address-selections?deviceType=desktop&pageType=Gateway&storeContext=NoStoreName&actionSource=desktop-modal> (referer: https://www.amazon.de)
Traceback (most recent call last):
  File "c:\users\cyril\appdata\local\programs\python\python39\lib\site-packages\twisted\internet\defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "D:\Bureau\amazon-location-cookies-service-master\main\spiders\locations.py", line 80, in parse_cookies
    csrf_token=self._get_csrf_token(response=response),
  File "D:\Bureau\amazon-location-cookies-service-master\main\spiders\locations.py", line 110, in _get_csrf_token
    raise ValueError("CSRF token not found")
ValueError: CSRF token not found
```
Do you have any fix for this situation ?

Thanks in advance,

**Comment by borys25ol** [comment]
@CSCyril 
Hello,
Thank you for your feedback. 
Seems like Amazon changed their endpoint for getting CSRF token and I've provided the fix.
Please try again.
